Comments section on Post Page
callback-demons/callback-news pull request #86
Opened 2020-05-26 05:05 UTC by WilliamVelazquez

Implementing the Comments Section at the end of the Post Page

2020-05-26 21:52 UTC, behagoras commented on pages/post.js
> +      {
Why doesn't We import the <CommentsSection /> component instead of calling the component in here

2020-05-26 21:53 UTC, behagoras commented on components/CommentsSection.js
> +function CommentsSection({ comments = {} }) {
The comments should be an array and should be iterated in the component, We're not using this component

2020-05-26 21:55 UTC, behagoras commented on components/CommentsSection.js
> +        Array.from(Array(5).keys()).map(() => <Comment text={testComment} />)
We should iterate between the comments array 
```javascript
comments.map((comment) => <Comment comment={comment} />
```

2020-05-26 22:00 UTC, behagoras requested changes
Should use the component `<CommentsSection />` (not imported) into the `post.js` page passing an array of `comments`

<CommentsSection comments={comments} />

2020-05-27 02:13 UTC, WilliamVelazquez reviewed
You're right, let me fix all that stuff.

2020-05-27 02:18 UTC, behagoras approved these changes
🥳

2020-05-27 02:19 UTC, merged